replicaCount: 1

image:
  repository: 82mtanveer/myrepo
  tag: flask-robot-arm64-final
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5002
  nodePort: 32392

env:
  ENVIRONMENT: staging
  LG_ADDR: localhost
  LG_PORT: 8889

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"
