apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-robot-prod
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-prod.yaml
    path: helm
    repoURL: https://github.com/mtanveer2016/flask-robot
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m