apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-robot-aiml.fullname" . }}
  labels:
    app: flask-robot-aiml
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-robot-aiml
  template:
    metadata:
      labels:
        app: flask-robot-aiml
    spec:
      securityContext:
        runAsUser: 0  # Run as root
        runAsGroup: 0
      containers:
      - name: flask-robot-aiml
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - IPC_LOCK
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.env.ENVIRONMENT }}"
        - name: LG_ADDR
          value: "{{ .Values.env.LG_ADDR | default "localhost" }}"
        - name: LG_PORT
          value: "{{ .Values.env.LG_PORT | default "8889" }}"
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        volumeMounts:
        - name: dev-gpiomem
          mountPath: /dev/gpiomem
        - name: dev-i2c
          mountPath: /dev/i2c-1
        - name: dev-mem
          mountPath: /dev/mem
      volumes:
      - name: dev-gpiomem
        hostPath:
          path: /dev/gpiomem
          type: CharDevice
      - name: dev-i2c
        hostPath:
          path: /dev/i2c-1
          type: CharDevice
      - name: dev-mem
        hostPath:
          path: /dev/mem
          type: CharDevice
