namespace:
  name: staging

replicaCount: 1

image:
  repository: 82mtanveer/myrepo
  tag: flask-robot-arm64-final
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5002
  targetPort: 5002
  nodePort: 32391
  protocol: TCP

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

ports:
  containerPort: 5002
  protocol: TCP

env:
  PIGPIO_ADDR: "10.226.22.234"
  PIGPIO_PORT: "8889"

securityContext:
  privileged: true

volumeMounts:
  - name: i2c-dev
    mountPath: /dev/i2c-1
  - name: dev-mem
    mountPath: /dev/mem
  - name: dev-gpiomem
    mountPath: /dev/gpiomem

volumes:
  - name: i2c-dev
    hostPath:
      path: /dev/i2c-1
  - name: dev-mem
    hostPath:
      path: /dev/mem
  - name: dev-gpiomem
    hostPath:
      path: /dev/gpiomem
